// PARTE 1 - GRUPOS A y B
export const PLAYERS_DB = [
  // --- GRUPO A ---
  // ALEMANIA
  { id: "GER-01", nombre: "Neuer", posicion: "POR", precio: 42, seleccion: "Alemania" },
  { id: "GER-02", nombre: "Ter Stegen", posicion: "POR", precio: 35, seleccion: "Alemania" },
  { id: "GER-03", nombre: "Baumann", posicion: "POR", precio: 15, seleccion: "Alemania" },
  { id: "GER-04", nombre: "Rüdiger", posicion: "DEF", precio: 48, seleccion: "Alemania" },
  { id: "GER-05", nombre: "Kimmich", posicion: "DEF", precio: 55, seleccion: "Alemania" },
  { id: "GER-06", nombre: "Tah", posicion: "DEF", precio: 40, seleccion: "Alemania" },
  { id: "GER-07", nombre: "Raum", posicion: "DEF", precio: 30, seleccion: "Alemania" },
  { id: "GER-08", nombre: "Mittelstädt", posicion: "DEF", precio: 28, seleccion: "Alemania" },
  { id: "GER-09", nombre: "Anton", posicion: "DEF", precio: 25, seleccion: "Alemania" },
  { id: "GER-10", nombre: "Henrichs", posicion: "DEF", precio: 25, seleccion: "Alemania" },
  { id: "GER-11", nombre: "Koch", posicion: "DEF", precio: 20, seleccion: "Alemania" },
  { id: "GER-12", nombre: "Kroos", posicion: "MED", precio: 55, seleccion: "Alemania" },
  { id: "GER-13", nombre: "Gündogan", posicion: "MED", precio: 50, seleccion: "Alemania" },
  { id: "GER-14", nombre: "Musiala", posicion: "MED", precio: 61, seleccion: "Alemania" },
  { id: "GER-15", nombre: "Wirtz", posicion: "MED", precio: 62, seleccion: "Alemania" },
  { id: "GER-16", nombre: "Andrich", posicion: "MED", precio: 25, seleccion: "Alemania" },
  { id: "GER-17", nombre: "Gross", posicion: "MED", precio: 25, seleccion: "Alemania" },
  { id: "GER-18", nombre: "Führich", posicion: "MED", precio: 20, seleccion: "Alemania" },
  { id: "GER-19", nombre: "Sané", posicion: "MED", precio: 48, seleccion: "Alemania" },
  { id: "GER-20", nombre: "Havertz", posicion: "DEL", precio: 52, seleccion: "Alemania" },
  { id: "GER-21", nombre: "Füllkrug", posicion: "DEL", precio: 38, seleccion: "Alemania" },
  { id: "GER-22", nombre: "Müller", posicion: "DEL", precio: 35, seleccion: "Alemania" },
  { id: "GER-23", nombre: "Undav", posicion: "DEL", precio: 30, seleccion: "Alemania" },
  { id: "GER-24", nombre: "Beier", posicion: "DEL", precio: 25, seleccion: "Alemania" },
  // ESCOCIA
  { id: "SCO-01", nombre: "Gunn", posicion: "POR", precio: 15, seleccion: "Escocia" },
  { id: "SCO-02", nombre: "Kelly", posicion: "POR", precio: 8, seleccion: "Escocia" },
  { id: "SCO-03", nombre: "Clark", posicion: "POR", precio: 8, seleccion: "Escocia" },
  { id: "SCO-04", nombre: "Robertson", posicion: "DEF", precio: 45, seleccion: "Escocia" },
  { id: "SCO-05", nombre: "Tierney", posicion: "DEF", precio: 35, seleccion: "Escocia" },
  { id: "SCO-06", nombre: "Hickey", posicion: "DEF", precio: 25, seleccion: "Escocia" },
  { id: "SCO-07", nombre: "Hendry", posicion: "DEF", precio: 15, seleccion: "Escocia" },
  { id: "SCO-08", nombre: "Porteous", posicion: "DEF", precio: 15, seleccion: "Escocia" },
  { id: "SCO-09", nombre: "Cooper", posicion: "DEF", precio: 12, seleccion: "Escocia" },
  { id: "SCO-10", nombre: "Souttar", posicion: "DEF", precio: 12, seleccion: "Escocia" },
  { id: "SCO-11", nombre: "Ralston", posicion: "DEF", precio: 10, seleccion: "Escocia" },
  { id: "SCO-12", nombre: "McTominay", posicion: "MED", precio: 35, seleccion: "Escocia" },
  { id: "SCO-13", nombre: "McGinn", posicion: "MED", precio: 30, seleccion: "Escocia" },
  { id: "SCO-14", nombre: "Gilmour", posicion: "MED", precio: 20, seleccion: "Escocia" },
  { id: "SCO-15", nombre: "McGregor", posicion: "MED", precio: 20, seleccion: "Escocia" },
  { id: "SCO-16", nombre: "Armstrong", posicion: "MED", precio: 15, seleccion: "Escocia" },
  { id: "SCO-17", nombre: "Christie", posicion: "MED", precio: 20, seleccion: "Escocia" },
  { id: "SCO-18", nombre: "McLean", posicion: "MED", precio: 12, seleccion: "Escocia" },
  { id: "SCO-19", nombre: "Jack", posicion: "MED", precio: 10, seleccion: "Escocia" },
  { id: "SCO-20", nombre: "Adams", posicion: "DEL", precio: 25, seleccion: "Escocia" },
  { id: "SCO-21", nombre: "Dykes", posicion: "DEL", precio: 20, seleccion: "Escocia" },
  { id: "SCO-22", nombre: "Shankland", posicion: "DEL", precio: 15, seleccion: "Escocia" },
  // HUNGRÍA
  { id: "HUN-01", nombre: "Gulácsi", posicion: "POR", precio: 20, seleccion: "Hungría" },
  { id: "HUN-02", nombre: "Dibusz", posicion: "POR", precio: 15, seleccion: "Hungría" },
  { id: "HUN-03", nombre: "Szappanos", posicion: "POR", precio: 8, seleccion: "Hungría" },
  { id: "HUN-04", nombre: "Orban", posicion: "DEF", precio: 30, seleccion: "Hungría" },
  { id: "HUN-05", nombre: "Szalai", posicion: "DEF", precio: 25, seleccion: "Hungría" },
  { id: "HUN-06", nombre: "Lang", posicion: "DEF", precio: 15, seleccion: "Hungría" },
  { id: "HUN-07", nombre: "Balogh", posicion: "DEF", precio: 10, seleccion: "Hungría" },
  { id: "HUN-08", nombre: "Botka", posicion: "DEF", precio: 10, seleccion: "Hungría" },
  { id: "HUN-09", nombre: "Dardai", posicion: "DEF", precio: 12, seleccion: "Hungría" },
  { id: "HUN-10", nombre: "Fiola", posicion: "DEF", precio: 10, seleccion: "Hungría" },
  { id: "HUN-11", nombre: "Szoboszlai", posicion: "MED", precio: 55, seleccion: "Hungría" },
  { id: "HUN-12", nombre: "Nagy", posicion: "MED", precio: 15, seleccion: "Hungría" },
  { id: "HUN-13", nombre: "Styles", posicion: "MED", precio: 15, seleccion: "Hungría" },
  { id: "HUN-14", nombre: "Schafer", posicion: "MED", precio: 18, seleccion: "Hungría" },
  { id: "HUN-15", nombre: "Kleinheisler", posicion: "MED", precio: 12, seleccion: "Hungría" },
  { id: "HUN-16", nombre: "Gazdag", posicion: "MED", precio: 15, seleccion: "Hungría" },
  { id: "HUN-17", nombre: "Sallai", posicion: "DEL", precio: 25, seleccion: "Hungría" },
  { id: "HUN-18", nombre: "Varga", posicion: "DEL", precio: 20, seleccion: "Hungría" },
  { id: "HUN-19", nombre: "Adam", posicion: "DEL", precio: 12, seleccion: "Hungría" },
  { id: "HUN-20", nombre: "Csoboth", posicion: "DEL", precio: 10, seleccion: "Hungría" },
  // SUIZA
  { id: "SUI-01", nombre: "Sommer", posicion: "POR", precio: 35, seleccion: "Suiza" },
  { id: "SUI-02", nombre: "Kobel", posicion: "POR", precio: 30, seleccion: "Suiza" },
  { id: "SUI-03", nombre: "Mvogo", posicion: "POR", precio: 10, seleccion: "Suiza" },
  { id: "SUI-04", nombre: "Akanji", posicion: "DEF", precio: 40, seleccion: "Suiza" },
  { id: "SUI-05", nombre: "Schär", posicion: "DEF", precio: 30, seleccion: "Suiza" },
  { id: "SUI-06", nombre: "Rodríguez", posicion: "DEF", precio: 25, seleccion: "Suiza" },
  { id: "SUI-07", nombre: "Elvedi", posicion: "DEF", precio: 22, seleccion: "Suiza" },
  { id: "SUI-08", nombre: "Widmer", posicion: "DEF", precio: 20, seleccion: "Suiza" },
  { id: "SUI-09", nombre: "Zesiger", posicion: "DEF", precio: 15, seleccion: "Suiza" },
  { id: "SUI-10", nombre: "Stergiou", posicion: "DEF", precio: 15, seleccion: "Suiza" },
  { id: "SUI-11", nombre: "Xhaka", posicion: "MED", precio: 40, seleccion: "Suiza" },
  { id: "SUI-12", nombre: "Freuler", posicion: "MED", precio: 25, seleccion: "Suiza" },
  { id: "SUI-13", nombre: "Shaqiri", posicion: "MED", precio: 28, seleccion: "Suiza" },
  { id: "SUI-14", nombre: "Zakaria", posicion: "MED", precio: 22, seleccion: "Suiza" },
  { id: "SUI-15", nombre: "Aebischer", posicion: "MED", precio: 18, seleccion: "Suiza" },
  { id: "SUI-16", nombre: "Rieder", posicion: "MED", precio: 18, seleccion: "Suiza" },
  { id: "SUI-17", nombre: "Sierro", posicion: "MED", precio: 15, seleccion: "Suiza" },
  { id: "SUI-18", nombre: "Embolo", posicion: "DEL", precio: 30, seleccion: "Suiza" },
  { id: "SUI-19", nombre: "Okafor", posicion: "DEL", precio: 25, seleccion: "Suiza" },
  { id: "SUI-20", nombre: "Amdouni", posicion: "DEL", precio: 22, seleccion: "Suiza" },
  { id: "SUI-21", nombre: "Vargas", posicion: "DEL", precio: 20, seleccion: "Suiza" },
  { id: "SUI-22", nombre: "Ndoye", posicion: "DEL", precio: 20, seleccion: "Suiza" },
  { id: "SUI-23", nombre: "Steffen", posicion: "DEL", precio: 15, seleccion: "Suiza" },
  { id: "SUI-24", nombre: "Duah", posicion: "DEL", precio: 15, seleccion: "Suiza" },
  // --- GRUPO B ---
  // ESPAÑA
  { id: "ESP-01", nombre: "Unai Simón", posicion: "POR", precio: 40, seleccion: "España" },
  { id: "ESP-02", nombre: "David Raya", posicion: "POR", precio: 25, seleccion: "España" },
  { id: "ESP-03", nombre: "Remiro", posicion: "POR", precio: 15, seleccion: "España" },
  { id: "ESP-04", nombre: "Carvajal", posicion: "DEF", precio: 45, seleccion: "España" },
  { id: "ESP-05", nombre: "Jesús Navas", posicion: "DEF", precio: 18, seleccion: "España" },
  { id: "ESP-06", nombre: "Laporte", posicion: "DEF", precio: 42, seleccion: "España" },
  { id: "ESP-07", nombre: "Le Normand", posicion: "DEF", precio: 38, seleccion: "España" },
  { id: "ESP-08", nombre: "Nacho", posicion: "DEF", precio: 25, seleccion: "España" },
  { id: "ESP-09", nombre: "Vivian", posicion: "DEF", precio: 25, seleccion: "España" },
  { id: "ESP-10", nombre: "Grimaldo", posicion: "DEF", precio: 48, seleccion: "España" },
  { id: "ESP-11", nombre: "Cucurella", posicion: "DEF", precio: 30, seleccion: "España" },
  { id: "ESP-12", nombre: "Rodri", posicion: "MED", precio: 61, seleccion: "España" },
  { id: "ESP-13", nombre: "Zubimendi", posicion: "MED", precio: 28, seleccion: "España" },
  { id: "ESP-14", nombre: "Mikel Merino", posicion: "MED", precio: 32, seleccion: "España" },
  { id: "ESP-15", nombre: "Fabián", posicion: "MED", precio: 35, seleccion: "España" },
  { id: "ESP-16", nombre: "Pedri", posicion: "MED", precio: 61, seleccion: "España" },
  { id: "ESP-17", nombre: "Fermín", posicion: "MED", precio: 25, seleccion: "España" },
  { id: "ESP-18", nombre: "Baena", posicion: "MED", precio: 25, seleccion: "España" },
  { id: "ESP-19", nombre: "Dani Olmo", posicion: "MED", precio: 45, seleccion: "España" },
  { id: "ESP-20", nombre: "Nico Williams", posicion: "DEL", precio: 55, seleccion: "España" },
  { id: "ESP-21", nombre: "Lamine Yamal", posicion: "DEL", precio: 58, seleccion: "España" },
  { id: "ESP-22", nombre: "Ferran Torres", posicion: "DEL", precio: 38, seleccion: "España" },
  { id: "ESP-23", nombre: "Morata", posicion: "DEL", precio: 48, seleccion: "España" },
  { id: "ESP-24", nombre: "Joselu", posicion: "DEL", precio: 25, seleccion: "España" },
  { id: "ESP-25", nombre: "Oyarzabal", posicion: "DEL", precio: 35, seleccion: "España" },
  { id: "ESP-26", nombre: "Ayoze", posicion: "DEL", precio: 20, seleccion: "España" },
  // CROACIA
  { id: "CRO-01", nombre: "Livakovic", posicion: "POR", precio: 35, seleccion: "Croacia" },
  { id: "CRO-02", nombre: "Ivusic", posicion: "POR", precio: 10, seleccion: "Croacia" },
  { id: "CRO-03", nombre: "Labrovic", posicion: "POR", precio: 10, seleccion: "Croacia" },
  { id: "CRO-04", nombre: "Gvardiol", posicion: "DEF", precio: 50, seleccion: "Croacia" },
  { id: "CRO-05", nombre: "Stanisic", posicion: "DEF", precio: 35, seleccion: "Croacia" },
  { id: "CRO-06", nombre: "Sutalo", posicion: "DEF", precio: 30, seleccion: "Croacia" },
  { id: "CRO-07", nombre: "Pongracic", posicion: "DEF", precio: 20, seleccion: "Croacia" },
  { id: "CRO-08", nombre: "Erlic", posicion: "DEF", precio: 15, seleccion: "Croacia" },
  { id: "CRO-09", nombre: "Vida", posicion: "DEF", precio: 15, seleccion: "Croacia" },
  { id: "CRO-10", nombre: "Juranovic", posicion: "DEF", precio: 25, seleccion: "Croacia" },
  { id: "CRO-11", nombre: "Sosa", posicion: "DEF", precio: 25, seleccion: "Croacia" },
  { id: "CRO-12", nombre: "Modric", posicion: "MED", precio: 50, seleccion: "Croacia" },
  { id: "CRO-13", nombre: "Kovacic", posicion: "MED", precio: 45, seleccion: "Croacia" },
  { id: "CRO-14", nombre: "Brozovic", posicion: "MED", precio: 40, seleccion: "Croacia" },
  { id: "CRO-15", nombre: "Majer", posicion: "MED", precio: 35, seleccion: "Croacia" },
  { id: "CRO-16", nombre: "Pasalic", posicion: "MED", precio: 30, seleccion: "Croacia" },
  { id: "CRO-17", nombre: "Sucic", posicion: "MED", precio: 25, seleccion: "Croacia" },
  { id: "CRO-18", nombre: "Ivanusec", posicion: "MED", precio: 25, seleccion: "Croacia" },
  { id: "CRO-19", nombre: "Baturina", posicion: "MED", precio: 20, seleccion: "Croacia" },
  { id: "CRO-20", nombre: "Kramaric", posicion: "DEL", precio: 38, seleccion: "Croacia" },
  { id: "CRO-21", nombre: "Budimir", posicion: "DEL", precio: 30, seleccion: "Croacia" },
  { id: "CRO-22", nombre: "Petkovic", posicion: "DEL", precio: 28, seleccion: "Croacia" },
  { id: "CRO-23", nombre: "Perisic", posicion: "DEL", precio: 35, seleccion: "Croacia" },
  { id: "CRO-24", nombre: "Pjaca", posicion: "DEL", precio: 20, seleccion: "Croacia" },
  { id: "CRO-25", nombre: "M. Pasalic", posicion: "DEL", precio: 15, seleccion: "Croacia" },
  // ITALIA
  { id: "ITA-01", nombre: "Donnarumma", posicion: "POR", precio: 50, seleccion: "Italia" },
  { id: "ITA-02", nombre: "Vicario", posicion: "POR", precio: 25, seleccion: "Italia" },
  { id: "ITA-03", nombre: "Meret", posicion: "POR", precio: 20, seleccion: "Italia" },
  { id: "ITA-04", nombre: "Di Lorenzo", posicion: "DEF", precio: 40, seleccion: "Italia" },
  { id: "ITA-05", nombre: "Bastoni", posicion: "DEF", precio: 48, seleccion: "Italia" },
  { id: "ITA-06", nombre: "Dimarco", posicion: "DEF", precio: 45, seleccion: "Italia" },
  { id: "ITA-07", nombre: "Mancini", posicion: "DEF", precio: 30, seleccion: "Italia" },
  { id: "ITA-08", nombre: "Darmian", posicion: "DEF", precio: 25, seleccion: "Italia" },
  { id: "ITA-09", nombre: "Buongiorno", posicion: "DEF", precio: 25, seleccion: "Italia" },
  { id: "ITA-10", nombre: "Calafiori", posicion: "DEF", precio: 25, seleccion: "Italia" },
  { id: "ITA-11", nombre: "Cambiaso", posicion: "DEF", precio: 20, seleccion: "Italia" },
  { id: "ITA-12", nombre: "Bellanova", posicion: "DEF", precio: 15, seleccion: "Italia" },
  { id: "ITA-13", nombre: "Gatti", posicion: "DEF", precio: 15, seleccion: "Italia" },
  { id: "ITA-14", nombre: "Barella", posicion: "MED", precio: 61, seleccion: "Italia" },
  { id: "ITA-15", nombre: "Jorginho", posicion: "MED", precio: 35, seleccion: "Italia" },
  { id: "ITA-16", nombre: "Pellegrini", posicion: "MED", precio: 42, seleccion: "Italia" },
  { id: "ITA-17", nombre: "Frattesi", posicion: "MED", precio: 38, seleccion: "Italia" },
  { id: "ITA-18", nombre: "Cristante", posicion: "MED", precio: 30, seleccion: "Italia" },
  { id: "ITA-19", nombre: "Fagioli", posicion: "MED", precio: 25, seleccion: "Italia" },
  { id: "ITA-20", nombre: "Folorunsho", posicion: "MED", precio: 20, seleccion: "Italia" },
  { id: "ITA-21", nombre: "Chiesa", posicion: "DEL", precio: 52, seleccion: "Italia" },
  { id: "ITA-22", nombre: "Scamacca", posicion: "DEL", precio: 40, seleccion: "Italia" },
  { id: "ITA-23", nombre: "Retegui", posicion: "DEL", precio: 30, seleccion: "Italia" },
  { id: "ITA-24", nombre: "Raspadori", posicion: "DEL", precio: 30, seleccion: "Italia" },
  { id: "ITA-25", nombre: "Zaccagni", posicion: "DEL", precio: 25, seleccion: "Italia" },
  { id: "ITA-26", nombre: "El Shaarawy", posicion: "DEL", precio: 25, seleccion: "Italia" },
  // ALBANIA
  { id: "ALB-01", nombre: "Strakosha", posicion: "POR", precio: 7, seleccion: "Albania" },
  { id: "ALB-02", nombre: "Berisha", posicion: "POR", precio: 7, seleccion: "Albania" },
  { id: "ALB-03", nombre: "Kastrati", posicion: "POR", precio: 7, seleccion: "Albania" },
  { id: "ALB-04", nombre: "Djimsiti", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-05", nombre: "Hysaj", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-06", nombre: "Mitaj", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-07", nombre: "Ismajli", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-08", nombre: "Ajeti", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-09", nombre: "Balliu", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-10", nombre: "Mihaj", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-11", nombre: "Kumbulla", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-12", nombre: "Aliji", posicion: "DEF", precio: 7, seleccion: "Albania" },
  { id: "ALB-13", nombre: "Asllani", posicion: "MED", precio: 8, seleccion: "Albania" },
  { id: "ALB-14", nombre: "Bajrami", posicion: "MED", precio: 8, seleccion: "Albania" },
  { id: "ALB-15", nombre: "Ramadani", posicion: "MED", precio: 7, seleccion: "Albania" },
  { id: "ALB-16", nombre: "Laci", posicion: "MED", precio: 7, seleccion: "Albania" },
  { id: "ALB-17", nombre: "Gjasula", posicion: "MED", precio: 7, seleccion: "Albania" },
  { id: "ALB-18", nombre: "Abrashi", posicion: "MED", precio: 7, seleccion: "Albania" },
  { id: "ALB-19", nombre: "Berisha", posicion: "MED", precio: 7, seleccion: "Albania" },
  { id: "ALB-20", nombre: "Broja", posicion: "DEL", precio: 9, seleccion: "Albania" },
  { id: "ALB-21", nombre: "Asani", posicion: "DEL", precio: 7, seleccion: "Albania" },
  { id: "ALB-22", nombre: "Seferi", posicion: "DEL", precio: 7, seleccion: "Albania" },
  { id: "ALB-23", nombre: "Manaj", posicion: "DEL", precio: 7, seleccion: "Albania" },
  { id: "ALB-24", nombre: "Daku", posicion: "DEL", precio: 7, seleccion: "Albania" },
  { id: "ALB-25", nombre: "Hoxha", posicion: "DEL", precio: 7, seleccion: "Albania" },
  { id: "ALB-26", nombre: "Muci", posicion: "DEL", precio: 7, seleccion: "Albania" },
  // --- GRUPO C ---
  // ESLOVENIA
  { id: "SVN-01", nombre: "Oblak", posicion: "POR", precio: 35, seleccion: "Eslovenia" },
  { id: "SVN-02", nombre: "Belec", posicion: "POR", precio: 7, seleccion: "Eslovenia" },
  { id: "SVN-03", nombre: "Vekic", posicion: "POR", precio: 7, seleccion: "Eslovenia" },
  { id: "SVN-04", nombre: "Bijol", posicion: "DEF", precio: 20, seleccion: "Eslovenia" },
  { id: "SVN-05", nombre: "Karnicnik", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-06", nombre: "Brekalo", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-07", nombre: "Drkusic", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-08", nombre: "Janza", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-09", nombre: "Stojanovic", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-10", nombre: "Balkovec", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-11", nombre: "Blazic", posicion: "DEF", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-12", nombre: "Gnezda Cerin", posicion: "MED", precio: 12, seleccion: "Eslovenia" },
  { id: "SVN-13", nombre: "Elsnik", posicion: "MED", precio: 12, seleccion: "Eslovenia" },
  { id: "SVN-14", nombre: "Lovric", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-15", nombre: "Gorenc Stankovic", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-16", nombre: "Horvat", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-17", nombre: "Kurtic", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-18", nombre: "Zeljkovic", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-19", nombre: "Verbic", posicion: "MED", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-20", nombre: "Sesko", posicion: "DEL", precio: 30, seleccion: "Eslovenia" },
  { id: "SVN-21", nombre: "Sporar", posicion: "DEL", precio: 20, seleccion: "Eslovenia" },
  { id: "SVN-22", nombre: "Mlakar", posicion: "DEL", precio: 15, seleccion: "Eslovenia" },
  { id: "SVN-23", nombre: "Vipotnik", posicion: "DEL", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-24", nombre: "Celar", posicion: "DEL", precio: 10, seleccion: "Eslovenia" },
  { id: "SVN-25", nombre: "Ilicic", posicion: "DEL", precio: 15, seleccion: "Eslovenia" },
  { id: "SVN-26", nombre: "Zugelj", posicion: "DEL", precio: 10, seleccion: "Eslovenia" },
  // DINAMARCA
  { id: "DEN-01", nombre: "Schmeichel", posicion: "POR", precio: 30, seleccion: "Dinamarca" },
  { id: "DEN-02", nombre: "Ronnow", posicion: "POR", precio: 10, seleccion: "Dinamarca" },
  { id: "DEN-03", nombre: "Hermansen", posicion: "POR", precio: 10, seleccion: "Dinamarca" },
  { id: "DEN-04", nombre: "Christensen", posicion: "DEF", precio: 40, seleccion: "Dinamarca" },
  { id: "DEN-05", nombre: "Andersen", posicion: "DEF", precio: 35, seleccion: "Dinamarca" },
  { id: "DEN-06", nombre: "Vestergaard", posicion: "DEF", precio: 30, seleccion: "Dinamarca" },
  { id: "DEN-07", nombre: "Maehle", posicion: "DEF", precio: 38, seleccion: "Dinamarca" },
  { id: "DEN-08", nombre: "Bah", posicion: "DEF", precio: 30, seleccion: "Dinamarca" },
  { id: "DEN-09", nombre: "Kristiansen", posicion: "DEF", precio: 25, seleccion: "Dinamarca" },
  { id: "DEN-10", nombre: "Kjaer", posicion: "DEF", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-11", nombre: "Nelsson", posicion: "DEF", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-12", nombre: "Eriksen", posicion: "MED", precio: 35, seleccion: "Dinamarca" },
  { id: "DEN-13", nombre: "Hojbjerg", posicion: "MED", precio: 30, seleccion: "Dinamarca" },
  { id: "DEN-14", nombre: "Delaney", posicion: "MED", precio: 25, seleccion: "Dinamarca" },
  { id: "DEN-15", nombre: "Norgaard", posicion: "MED", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-16", nombre: "Hjulmand", posicion: "MED", precio: 25, seleccion: "Dinamarca" },
  { id: "DEN-17", nombre: "Jensen", posicion: "MED", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-18", nombre: "Hojlund", posicion: "DEL", precio: 45, seleccion: "Dinamarca" },
  { id: "DEN-19", nombre: "Wind", posicion: "DEL", precio: 25, seleccion: "Dinamarca" },
  { id: "DEN-20", nombre: "Poulsen", posicion: "DEL", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-21", nombre: "Dolberg", posicion: "DEL", precio: 20, seleccion: "Dinamarca" },
  { id: "DEN-22", nombre: "Skov Olsen", posicion: "DEL", precio: 25, seleccion: "Dinamarca" },
  { id: "DEN-23", nombre: "Damsgaard", posicion: "DEL", precio: 22, seleccion: "Dinamarca" },
  { id: "DEN-24", nombre: "Bruun Larsen", posicion: "DEL", precio: 15, seleccion: "Dinamarca" },
  { id: "DEN-25", nombre: "Dreyer", posicion: "DEL", precio: 15, seleccion: "Dinamarca" },
  // SERBIA
  { id: "SRB-01", nombre: "V. Milinkovic-Savic", posicion: "POR", precio: 15, seleccion: "Serbia" },
  { id: "SRB-02", nombre: "Rajkovic", posicion: "POR", precio: 15, seleccion: "Serbia" },
  { id: "SRB-03", nombre: "Petrovic", posicion: "POR", precio: 10, seleccion: "Serbia" },
  { id: "SRB-04", nombre: "Milenkovic", posicion: "DEF", precio: 20, seleccion: "Serbia" },
  { id: "SRB-05", nombre: "Pavlovic", posicion: "DEF", precio: 20, seleccion: "Serbia" },
  { id: "SRB-06", nombre: "Veljkovic", posicion: "DEF", precio: 15, seleccion: "Serbia" },
  { id: "SRB-07", nombre: "Babic", posicion: "DEF", precio: 12, seleccion: "Serbia" },
  { id: "SRB-08", nombre: "Spajic", posicion: "DEF", precio: 10, seleccion: "Serbia" },
  { id: "SRB-09", nombre: "Stojic", posicion: "DEF", precio: 10, seleccion: "Serbia" },
  { id: "SRB-10", nombre: "Gudelj", posicion: "DEF", precio: 15, seleccion: "Serbia" },
  { id: "SRB-11", nombre: "Mladenovic", posicion: "DEF", precio: 12, seleccion: "Serbia" },
  { id: "SRB-12", nombre: "S. Milinkovic-Savic", posicion: "MED", precio: 35, seleccion: "Serbia" },
  { id: "SRB-13", nombre: "Tadic", posicion: "MED", precio: 30, seleccion: "Serbia" },
  { id: "SRB-14", nombre: "Kostic", posicion: "MED", precio: 25, seleccion: "Serbia" },
  { id: "SRB-15", nombre: "Zivkovic", posicion: "MED", precio: 20, seleccion: "Serbia" },
  { id: "SRB-16", nombre: "Lukic", posicion: "MED", precio: 20, seleccion: "Serbia" },
  { id: "SRB-17", nombre: "Ilic", posicion: "MED", precio: 18, seleccion: "Serbia" },
  { id: "SRB-18", nombre: "Maksimovic", posicion: "MED", precio: 15, seleccion: "Serbia" },
  { id: "SRB-19", nombre: "Mijailovic", posicion: "MED", precio: 10, seleccion: "Serbia" },
  { id: "SRB-20", nombre: "Samardzic", posicion: "MED", precio: 20, seleccion: "Serbia" },
  { id: "SRB-21", nombre: "Gacinovic", posicion: "MED", precio: 15, seleccion: "Serbia" },
  { id: "SRB-22", nombre: "Birmancevic", posicion: "MED", precio: 15, seleccion: "Serbia" },
  { id: "SRB-23", nombre: "Vlahovic", posicion: "DEL", precio: 45, seleccion: "Serbia" },
  { id: "SRB-24", nombre: "Mitrovic", posicion: "DEL", precio: 40, seleccion: "Serbia" },
  { id: "SRB-25", nombre: "Jovic", posicion: "DEL", precio: 25, seleccion: "Serbia" },
  { id: "SRB-26", nombre: "Ratkov", posicion: "DEL", precio: 15, seleccion: "Serbia" },
  // INGLATERRA
  { id: "ENG-01", nombre: "Pickford", posicion: "POR", precio: 40, seleccion: "Inglaterra" },
  { id: "ENG-02", nombre: "Ramsdale", posicion: "POR", precio: 20, seleccion: "Inglaterra" },
  { id: "ENG-03", nombre: "Henderson", posicion: "POR", precio: 15, seleccion: "Inglaterra" },
  { id: "ENG-04", nombre: "Walker", posicion: "DEF", precio: 48, seleccion: "Inglaterra" },
  { id: "ENG-05", nombre: "Stones", posicion: "DEF", precio: 50, seleccion: "Inglaterra" },
  { id: "ENG-06", nombre: "Trippier", posicion: "DEF", precio: 42, seleccion: "Inglaterra" },
  { id: "ENG-07", nombre: "Maguire", posicion: "DEF", precio: 35, seleccion: "Inglaterra" },
  { id: "ENG-08", nombre: "Guehi", posicion: "DEF", precio: 30, seleccion: "Inglaterra" },
  { id: "ENG-09", nombre: "Shaw", posicion: "DEF", precio: 35, seleccion: "Inglaterra" },
  { id: "ENG-10", nombre: "Konsa", posicion: "DEF", precio: 25, seleccion: "Inglaterra" },
  { id: "ENG-11", nombre: "Dunk", posicion: "DEF", precio: 20, seleccion: "Inglaterra" },
  { id: "ENG-12", nombre: "Gomez", posicion: "DEF", precio: 25, seleccion: "Inglaterra" },
  { id: "ENG-13", nombre: "Alexander-Arnold", posicion: "DEF", precio: 55, seleccion: "Inglaterra" },
  { id: "ENG-14", nombre: "Rice", posicion: "MED", precio: 61, seleccion: "Inglaterra" },
  { id: "ENG-15", nombre: "Bellingham", posicion: "MED", precio: 64, seleccion: "Inglaterra" },
  { id: "ENG-16", nombre: "Foden", posicion: "MED", precio: 60, seleccion: "Inglaterra" },
  { id: "ENG-17", nombre: "Gallagher", posicion: "MED", precio: 30, seleccion: "Inglaterra" },
  { id: "ENG-18", nombre: "Mainoo", posicion: "MED", precio: 25, seleccion: "Inglaterra" },
  { id: "ENG-19", nombre: "Wharton", posicion: "MED", precio: 15, seleccion: "Inglaterra" },
  { id: "ENG-20", nombre: "Palmer", posicion: "MED", precio: 45, seleccion: "Inglaterra" },
  { id: "ENG-21", nombre: "Saka", posicion: "DEL", precio: 58, seleccion: "Inglaterra" },
  { id: "ENG-22", nombre: "Kane", posicion: "DEL", precio: 61, seleccion: "Inglaterra" },
  { id: "ENG-23", nombre: "Watkins", posicion: "DEL", precio: 40, seleccion: "Inglaterra" },
  { id: "ENG-24", nombre: "Toney", posicion: "DEL", precio: 35, seleccion: "Inglaterra" },
  { id: "ENG-25", nombre: "Gordon", posicion: "DEL", precio: 30, seleccion: "Inglaterra" },
  { id: "ENG-26", nombre: "Eze", posicion: "DEL", precio: 30, seleccion: "Inglaterra" },
  { id: "ENG-27", nombre: "Bowen", posicion: "DEL", precio: 30, seleccion: "Inglaterra" },
  // --- GRUPO D ---
  // POLONIA
  { id: "POL-01", nombre: "Szczesny", posicion: "POR", precio: 30, seleccion: "Polonia" },
  { id: "POL-02", nombre: "Skorupski", posicion: "POR", precio: 10, seleccion: "Polonia" },
  { id: "POL-03", nombre: "Bulka", posicion: "POR", precio: 10, seleccion: "Polonia" },
  { id: "POL-04", nombre: "Kiwior", posicion: "DEF", precio: 25, seleccion: "Polonia" },
  { id: "POL-05", nombre: "Bednarek", posicion: "DEF", precio: 20, seleccion: "Polonia" },
  { id: "POL-06", nombre: "Dawidowicz", posicion: "DEF", precio: 15, seleccion: "Polonia" },
  { id: "POL-07", nombre: "Walukiewicz", posicion: "DEF", precio: 15, seleccion: "Polonia" },
  { id: "POL-08", nombre: "Salamon", posicion: "DEF", precio: 10, seleccion: "Polonia" },
  { id: "POL-09", nombre: "Bereszynski", posicion: "DEF", precio: 15, seleccion: "Polonia" },
  { id: "POL-10", nombre: "Puchacz", posicion: "DEF", precio: 12, seleccion: "Polonia" },
  { id: "POL-11", nombre: "Zielinski", posicion: "MED", precio: 35, seleccion: "Polonia" },
  { id: "POL-12", nombre: "Frankowski", posicion: "MED", precio: 20, seleccion: "Polonia" },
  { id: "POL-13", nombre: "Zalewski", posicion: "MED", precio: 20, seleccion: "Polonia" },
  { id: "POL-14", nombre: "Slisz", posicion: "MED", precio: 15, seleccion: "Polonia" },
  { id: "POL-15", nombre: "S. Szymanski", posicion: "MED", precio: 20, seleccion: "Polonia" },
  { id: "POL-16", nombre: "Piotrowski", posicion: "MED", precio: 15, seleccion: "Polonia" },
  { id: "POL-17", nombre: "Moder", posicion: "MED", precio: 15, seleccion: "Polonia" },
  { id: "POL-18", nombre: "Romanczuk", posicion: "MED", precio: 10, seleccion: "Polonia" },
  { id: "POL-19", nombre: "D. Szymanski", posicion: "MED", precio: 10, seleccion: "Polonia" },
  { id: "POL-20", nombre: "Urbanski", posicion: "MED", precio: 10, seleccion: "Polonia" },
  { id: "POL-21", nombre: "Grosicki", posicion: "MED", precio: 10, seleccion: "Polonia" },
  { id: "POL-22", nombre: "Skoras", posicion: "MED", precio: 10, seleccion: "Polonia" },
  { id: "POL-23", nombre: "Lewandowski", posicion: "DEL", precio: 55, seleccion: "Polonia" },
  { id: "POL-24", nombre: "Swiderski", posicion: "DEL", precio: 20, seleccion: "Polonia" },
  { id: "POL-25", nombre: "Buksa", posicion: "DEL", precio: 15, seleccion: "Polonia" },
  { id: "POL-26", nombre: "Piatek", posicion: "DEL", precio: 15, seleccion: "Polonia" },
  // PAÍSES BAJOS
  { id: "NED-01", nombre: "Verbruggen", posicion: "POR", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-02", nombre: "Flekken", posicion: "POR", precio: 15, seleccion: "Países Bajos" },
  { id: "NED-03", nombre: "Bijlow", posicion: "POR", precio: 15, seleccion: "Países Bajos" },
  { id: "NED-04", nombre: "Dumfries", posicion: "DEF", precio: 48, seleccion: "Países Bajos" },
  { id: "NED-05", nombre: "Van Dijk", posicion: "DEF", precio: 55, seleccion: "Países Bajos" },
  { id: "NED-06", nombre: "Aké", posicion: "DEF", precio: 45, seleccion: "Países Bajos" },
  { id: "NED-07", nombre: "Frimpong", posicion: "DEF", precio: 50, seleccion: "Países Bajos" },
  { id: "NED-08", nombre: "De Ligt", posicion: "DEF", precio: 40, seleccion: "Países Bajos" },
  { id: "NED-09", nombre: "De Vrij", posicion: "DEF", precio: 30, seleccion: "Países Bajos" },
  { id: "NED-10", nombre: "Van de Ven", posicion: "DEF", precio: 35, seleccion: "Países Bajos" },
  { id: "NED-11", nombre: "Geertruida", posicion: "DEF", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-12", nombre: "Blind", posicion: "DEF", precio: 20, seleccion: "Países Bajos" },
  { id: "NED-13", nombre: "Maatsen", posicion: "DEF", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-14", nombre: "Reijnders", posicion: "MED", precio: 35, seleccion: "Países Bajos" },
  { id: "NED-15", nombre: "Schouten", posicion: "MED", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-16", nombre: "Veerman", posicion: "MED", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-17", nombre: "Simons", posicion: "MED", precio: 55, seleccion: "Países Bajos" },
  { id: "NED-18", nombre: "Wijnaldum", posicion: "MED", precio: 20, seleccion: "Países Bajos" },
  { id: "NED-19", nombre: "Gravenberch", posicion: "MED", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-20", nombre: "Gakpo", posicion: "DEL", precio: 50, seleccion: "Países Bajos" },
  { id: "NED-21", nombre: "Depay", posicion: "DEL", precio: 45, seleccion: "Países Bajos" },
  { id: "NED-22", nombre: "Malen", posicion: "DEL", precio: 30, seleccion: "Países Bajos" },
  { id: "NED-23", nombre: "Weghorst", posicion: "DEL", precio: 20, seleccion: "Países Bajos" },
  { id: "NED-24", nombre: "Bergwijn", posicion: "DEL", precio: 25, seleccion: "Países Bajos" },
  { id: "NED-25", nombre: "Brobbey", posicion: "DEL", precio: 20, seleccion: "Países Bajos" },
  { id: "NED-26", nombre: "Zirkzee", posicion: "DEL", precio: 25, seleccion: "Países Bajos" },
  // AUSTRIA
  { id: "AUT-01", nombre: "Pentz", posicion: "POR", precio: 10, seleccion: "Austria" },
  { id: "AUT-02", nombre: "Lindner", posicion: "POR", precio: 10, seleccion: "Austria" },
  { id: "AUT-03", nombre: "Hedl", posicion: "POR", precio: 8, seleccion: "Austria" },
  { id: "AUT-04", nombre: "Posch", posicion: "DEF", precio: 20, seleccion: "Austria" },
  { id: "AUT-05", nombre: "Danso", posicion: "DEF", precio: 18, seleccion: "Austria" },
  { id: "AUT-06", nombre: "Lienhart", posicion: "DEF", precio: 18, seleccion: "Austria" },
  { id: "AUT-07", nombre: "Wöber", posicion: "DEF", precio: 15, seleccion: "Austria" },
  { id: "AUT-08", nombre: "Mwene", posicion: "DEF", precio: 15, seleccion: "Austria" },
  { id: "AUT-09", nombre: "Trauner", posicion: "DEF", precio: 12, seleccion: "Austria" },
  { id: "AUT-10", nombre: "Querfeld", posicion: "DEF", precio: 10, seleccion: "Austria" },
  { id: "AUT-11", nombre: "Daniliuc", posicion: "DEF", precio: 10, seleccion: "Austria" },
  { id: "AUT-12", nombre: "Sabitzer", posicion: "MED", precio: 40, seleccion: "Austria" },
  { id: "AUT-13", nombre: "Laimer", posicion: "MED", precio: 35, seleccion: "Austria" },
  { id: "AUT-14", nombre: "Baumgartner", posicion: "MED", precio: 30, seleccion: "Austria" },
  { id: "AUT-15", nombre: "Seiwald", posicion: "MED", precio: 25, seleccion: "Austria" },
  { id: "AUT-16", nombre: "Wimmer", posicion: "MED", precio: 20, seleccion: "Austria" },
  { id: "AUT-17", nombre: "Grillitsch", posicion: "MED", precio: 15, seleccion: "Austria" },
  { id: "AUT-18", nombre: "Schmid", posicion: "MED", precio: 15, seleccion: "Austria" },
  { id: "AUT-19", nombre: "Kainz", posicion: "MED", precio: 12, seleccion: "Austria" },
  { id: "AUT-20", nombre: "Prass", posicion: "MED", precio: 12, seleccion: "Austria" },
  { id: "AUT-21", nombre: "Seidl", posicion: "MED", precio: 10, seleccion: "Austria" },
  { id: "AUT-22", nombre: "Arnautovic", posicion: "DEL", precio: 25, seleccion: "Austria" },
  { id: "AUT-23", nombre: "Gregoritsch", posicion: "DEL", precio: 20, seleccion: "Austria" },
  { id: "AUT-24", nombre: "Weimann", posicion: "DEL", precio: 12, seleccion: "Austria" },
  { id: "AUT-25", nombre: "Entrup", posicion: "DEL", precio: 10, seleccion: "Austria" },
  { id: "AUT-26", nombre: "Grüll", posicion: "DEL", precio: 10, seleccion: "Austria" },
  // FRANCIA
  { id: "FRA-01", nombre: "Maignan", posicion: "POR", precio: 45, seleccion: "Francia" },
  { id: "FRA-02", nombre: "Samba", posicion: "POR", precio: 15, seleccion: "Francia" },
  { id: "FRA-03", nombre: "Areola", posicion: "POR", precio: 15, seleccion: "Francia" },
  { id: "FRA-04", nombre: "Koundé", posicion: "DEF", precio: 48, seleccion: "Francia" },
  { id: "FRA-05", nombre: "Clauss", posicion: "DEF", precio: 35, seleccion: "Francia" },
  { id: "FRA-06", nombre: "Upamecano", posicion: "DEF", precio: 45, seleccion: "Francia" },
  { id: "FRA-07", nombre: "Konaté", posicion: "DEF", precio: 42, seleccion: "Francia" },
  { id: "FRA-08", nombre: "Saliba", posicion: "DEF", precio: 50, seleccion: "Francia" },
  { id: "FRA-09", nombre: "Theo Hernández", posicion: "DEF", precio: 55, seleccion: "Francia" },
  { id: "FRA-10", nombre: "Mendy", posicion: "DEF", precio: 35, seleccion: "Francia" },
  { id: "FRA-11", nombre: "Pavard", posicion: "DEF", precio: 38, seleccion: "Francia" },
  { id: "FRA-12", nombre: "Camavinga", posicion: "MED", precio: 52, seleccion: "Francia" },
  { id: "FRA-13", nombre: "Tchouaméni", posicion: "MED", precio: 61, seleccion: "Francia" },
  { id: "FRA-14", nombre: "Rabiot", posicion: "MED", precio: 40, seleccion: "Francia" },
  { id: "FRA-15", nombre: "Zaire-Emery", posicion: "MED", precio: 25, seleccion: "Francia" },
  { id: "FRA-16", nombre: "Griezmann", posicion: "MED", precio: 61, seleccion: "Francia" },
  { id: "FRA-17", nombre: "Kanté", posicion: "MED", precio: 35, seleccion: "Francia" },
  { id: "FRA-18", nombre: "Fofana", posicion: "MED", precio: 25, seleccion: "Francia" },
  { id: "FRA-19", nombre: "Dembélé", posicion: "DEL", precio: 55, seleccion: "Francia" },
  { id: "FRA-20", nombre: "Mbappé", posicion: "DEL", precio: 75, seleccion: "Francia" },
  { id: "FRA-21", nombre: "Coman", posicion: "DEL", precio: 45, seleccion: "Francia" },
  { id: "FRA-22", nombre: "Thuram", posicion: "DEL", precio: 42, seleccion: "Francia" },
  { id: "FRA-23", nombre: "Giroud", posicion: "DEL", precio: 35, seleccion: "Francia" },
  { id: "FRA-24", nombre: "Kolo Muani", posicion: "DEL", precio: 40, seleccion: "Francia" },
  { id: "FRA-25", nombre: "Barcola", posicion: "DEL", precio: 28, seleccion: "Francia" },
  // --- GRUPO E ---
  // BÉLGICA
  { id: "BEL-01", nombre: "Casteels", posicion: "POR", precio: 30, seleccion: "Bélgica" },
  { id: "BEL-02", nombre: "Sels", posicion: "POR", precio: 15, seleccion: "Bélgica" },
  { id: "BEL-03", nombre: "Kaminski", posicion: "POR", precio: 10, seleccion: "Bélgica" },
  { id: "BEL-04", nombre: "Castagne", posicion: "DEF", precio: 35, seleccion: "Bélgica" },
  { id: "BEL-05", nombre: "Faes", posicion: "DEF", precio: 25, seleccion: "Bélgica" },
  { id: "BEL-06", nombre: "Vertonghen", posicion: "DEF", precio: 20, seleccion: "Bélgica" },
  { id: "BEL-07", nombre: "Theate", posicion: "DEF", precio: 25, seleccion: "Bélgica" },
  { id: "BEL-08", nombre: "Debast", posicion: "DEF", precio: 20, seleccion: "Bélgica" },
  { id: "BEL-09", nombre: "Meunier", posicion: "DEF", precio: 20, seleccion: "Bélgica" },
  { id: "BEL-10", nombre: "Witsel", posicion: "DEF", precio: 20, seleccion: "Bélgica" },
  { id: "BEL-11", nombre: "De Bruyne", posicion: "MED", precio: 63, seleccion: "Bélgica" },
  { id: "BEL-12", nombre: "Onana", posicion: "MED", precio: 35, seleccion: "Bélgica" },
  { id: "BEL-13", nombre: "Tielemans", posicion: "MED", precio: 38, seleccion: "Bélgica" },
  { id: "BEL-14", nombre: "Mangala", posicion: "MED", precio: 20, seleccion: "Bélgica" },
  { id: "BEL-15", nombre: "Vermeeren", posicion: "MED", precio: 18, seleccion: "Bélgica" },
  { id: "BEL-16", nombre: "Vranckx", posicion: "MED", precio: 15, seleccion: "Bélgica" },
  { id: "BEL-17", nombre: "De Cuyper", posicion: "DEF", precio: 15, seleccion: "Bélgica" },
  { id: "BEL-18", nombre: "Doku", posicion: "DEL", precio: 52, seleccion: "Bélgica" },
  { id: "BEL-19", nombre: "Lukaku", posicion: "DEL", precio: 58, seleccion: "Bélgica" },
  { id: "BEL-20", nombre: "Trossard", posicion: "DEL", precio: 45, seleccion: "Bélgica" },
  { id: "BEL-21", nombre: "Openda", posicion: "DEL", precio: 30, seleccion: "Bélgica" },
  { id: "BEL-22", nombre: "Bakayoko", posicion: "DEL", precio: 25, seleccion: "Bélgica" },
  { id: "BEL-23", nombre: "Carrasco", posicion: "DEL", precio: 30, seleccion: "Bélgica" },
  { id: "BEL-24", nombre: "De Ketelaere", posicion: "DEL", precio: 25, seleccion: "Bélgica" },
  { id: "BEL-25", nombre: "Lukebakio", posicion: "DEL", precio: 20, seleccion: "Bélgica" },
  // ESLOVAQUIA
  { id: "SVK-01", nombre: "Dubravka", posicion: "POR", precio: 15, seleccion: "Eslovaquia" },
  { id: "SVK-02", nombre: "Rodak", posicion: "POR", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-03", nombre: "Ravas", posicion: "POR", precio: 7, seleccion: "Eslovaquia" },
  { id: "SVK-04", nombre: "Skriniar", posicion: "DEF", precio: 35, seleccion: "Eslovaquia" },
  { id: "SVK-05", nombre: "Hancko", posicion: "DEF", precio: 30, seleccion: "Eslovaquia" },
  { id: "SVK-06", nombre: "Vavro", posicion: "DEF", precio: 15, seleccion: "Eslovaquia" },
  { id: "SVK-07", nombre: "Pekarik", posicion: "DEF", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-08", nombre: "Gyomber", posicion: "DEF", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-09", nombre: "Obert", posicion: "DEF", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-10", nombre: "De Marco", posicion: "DEF", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-11", nombre: "Kosa", posicion: "DEF", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-12", nombre: "Lobotka", posicion: "MED", precio: 25, seleccion: "Eslovaquia" },
  { id: "SVK-13", nombre: "Duda", posicion: "MED", precio: 20, seleccion: "Eslovaquia" },
  { id: "SVK-14", nombre: "Kucka", posicion: "MED", precio: 15, seleccion: "Eslovaquia" },
  { id: "SVK-15", nombre: "Benes", posicion: "MED", precio: 12, seleccion: "Eslovaquia" },
  { id: "SVK-16", nombre: "Hrosovsky", posicion: "MED", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-17", nombre: "Rigo", posicion: "MED", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-18", nombre: "Bero", posicion: "MED", precio: 8, seleccion: "Eslovaquia" },
  { id: "SVK-19", nombre: "Haraslin", posicion: "DEL", precio: 15, seleccion: "Eslovaquia" },
  { id: "SVK-20", nombre: "Schranz", posicion: "DEL", precio: 15, seleccion: "Eslovaquia" },
  { id: "SVK-21", nombre: "Bozenik", posicion: "DEL", precio: 12, seleccion: "Eslovaquia" },
  { id: "SVK-22", nombre: "Suslov", posicion: "DEL", precio: 12, seleccion: "Eslovaquia" },
  { id: "SVK-23", nombre: "Strelec", posicion: "DEL", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-24", nombre: "Duris", posicion: "DEL", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-25", nombre: "Tupta", posicion: "DEL", precio: 10, seleccion: "Eslovaquia" },
  { id: "SVK-26", nombre: "Sauer", posicion: "DEL", precio: 10, seleccion: "Eslovaquia" },
  // RUMANÍA
  { id: "ROU-01", nombre: "Moldovan", posicion: "POR", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-02", nombre: "Nita", posicion: "POR", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-03", nombre: "Tarnovanu", posicion: "POR", precio: 7, seleccion: "Rumanía" },
  { id: "ROU-04", nombre: "Dragusin", posicion: "DEF", precio: 25, seleccion: "Rumanía" },
  { id: "ROU-05", nombre: "Burca", posicion: "DEF", precio: 15, seleccion: "Rumanía" },
  { id: "ROU-06", nombre: "Ratiu", posicion: "DEF", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-07", nombre: "Bancu", posicion: "DEF", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-08", nombre: "Mogos", posicion: "DEF", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-09", nombre: "Rus", posicion: "DEF", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-10", nombre: "Racovitan", posicion: "DEF", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-11", nombre: "Nedelcearu", posicion: "DEF", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-12", nombre: "Stanciu", posicion: "MED", precio: 15, seleccion: "Rumanía" },
  { id: "ROU-13", nombre: "R. Marin", posicion: "MED", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-14", nombre: "M. Marin", posicion: "MED", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-15", nombre: "Hagi", posicion: "MED", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-16", nombre: "Olaru", posicion: "MED", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-17", nombre: "Sut", posicion: "MED", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-18", nombre: "Cicaldau", posicion: "MED", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-19", nombre: "Sorescu", posicion: "MED", precio: 8, seleccion: "Rumanía" },
  { id: "ROU-20", nombre: "Grameni", posicion: "MED", precio: 7, seleccion: "Rumanía" },
  { id: "ROU-21", nombre: "Man", posicion: "DEL", precio: 15, seleccion: "Rumanía" },
  { id: "ROU-22", nombre: "Dragus", posicion: "DEL", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-23", nombre: "Mihaila", posicion: "DEL", precio: 12, seleccion: "Rumanía" },
  { id: "ROU-24", nombre: "Coman", posicion: "DEL", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-25", nombre: "Puscas", posicion: "DEL", precio: 10, seleccion: "Rumanía" },
  { id: "ROU-26", nombre: "Alibec", posicion: "DEL", precio: 10, seleccion: "Rumanía" },
  // UCRANIA
  { id: "UKR-01", nombre: "Lunin", posicion: "POR", precio: 35, seleccion: "Ucrania" },
  { id: "UKR-02", nombre: "Trubin", posicion: "POR", precio: 17, seleccion: "Ucrania" },
  { id: "UKR-03", nombre: "Bushchan", posicion: "POR", precio: 10, seleccion: "Ucrania" },
  { id: "UKR-04", nombre: "Zinchenko", posicion: "DEF", precio: 40, seleccion: "Ucrania" },
  { id: "UKR-05", nombre: "Mykolenko", posicion: "DEF", precio: 25, seleccion: "Ucrania" },
  { id: "UKR-06", nombre: "Zabarnyi", posicion: "DEF", precio: 25, seleccion: "Ucrania" },
  { id: "UKR-07", nombre: "Matviyenko", posicion: "DEF", precio: 20, seleccion: "Ucrania" },
  { id: "UKR-08", nombre: "Konoplya", posicion: "DEF", precio: 15, seleccion: "Ucrania" },
  { id: "UKR-09", nombre: "Tymchyk", posicion: "DEF", precio: 12, seleccion: "Ucrania" },
  { id: "UKR-10", nombre: "Bondar", posicion: "DEF", precio: 10, seleccion: "Ucrania" },
  { id: "UKR-11", nombre: "Svatok", posicion: "DEF", precio: 8, seleccion: "Ucrania" },
  { id: "UKR-12", nombre: "Talovierov", posicion: "DEF", precio: 8, seleccion: "Ucrania" },
  { id: "UKR-13", nombre: "Mudryk", posicion: "MED", precio: 45, seleccion: "Ucrania" },
  { id: "UKR-14", nombre: "Sudakov", posicion: "MED", precio: 30, seleccion: "Ucrania" },
  { id: "UKR-15", nombre: "Tsygankov", posicion: "MED", precio: 35, seleccion: "Ucrania" },
  { id: "UKR-16", nombre: "Shaparenko", posicion: "MED", precio: 20, seleccion: "Ucrania" },
  { id: "UKR-17", nombre: "Stepanenko", posicion: "MED", precio: 15, seleccion: "Ucrania" },
  { id: "UKR-18", nombre: "Malinovskyi", posicion: "MED", precio: 20, seleccion: "Ucrania" },
  { id: "UKR-19", nombre: "Brazhko", posicion: "MED", precio: 12, seleccion: "Ucrania" },
  { id: "UKR-20", nombre: "Sydorchuk", posicion: "MED", precio: 10, seleccion: "Ucrania" },
  { id: "UKR-21", nombre: "Zubkov", posicion: "MED", precio: 12, seleccion: "Ucrania" },
  { id: "UKR-22", nombre: "Dovbyk", posicion: "DEL", precio: 45, seleccion: "Ucrania" },
  { id: "UKR-23", nombre: "Yaremchuk", posicion: "DEL", precio: 20, seleccion: "Ucrania" },
  { id: "UKR-24", nombre: "Vanat", posicion: "DEL", precio: 10, seleccion: "Ucrania" },
  { id: "UKR-25", nombre: "Yarmolenko", posicion: "DEL", precio: 15, seleccion: "Ucrania" },
  // --- GRUPO F ---
  // TURQUÍA
  { id: "TUR-01", nombre: "Cakir", posicion: "POR", precio: 15, seleccion: "Turquía" },
  { id: "TUR-02", nombre: "Gunok", posicion: "POR", precio: 10, seleccion: "Turquía" },
  { id: "TUR-03", nombre: "Bayindir", posicion: "POR", precio: 10, seleccion: "Turquía" },
  { id: "TUR-04", nombre: "Kadioglu", posicion: "DEF", precio: 25, seleccion: "Turquía" },
  { id: "TUR-05", nombre: "Demiral", posicion: "DEF", precio: 20, seleccion: "Turquía" },
  { id: "TUR-06", nombre: "Bardakci", posicion: "DEF", precio: 15, seleccion: "Turquía" },
  { id: "TUR-07", nombre: "Celik", posicion: "DEF", precio: 15, seleccion: "Turquía" },
  { id: "TUR-08", nombre: "Muldur", posicion: "DEF", precio: 12, seleccion: "Turquía" },
  { id: "TUR-09", nombre: "Akaydin", posicion: "DEF", precio: 10, seleccion: "Turquía" },
  { id: "TUR-10", nombre: "Kaplan", posicion: "DEF", precio: 10, seleccion: "Turquía" },
  { id: "TUR-11", nombre: "Çalhanoglu", posicion: "MED", precio: 45, seleccion: "Turquía" },
  { id: "TUR-12", nombre: "Kokcu", posicion: "MED", precio: 30, seleccion: "Turquía" },
  { id: "TUR-13", nombre: "Arda Güler", posicion: "MED", precio: 35, seleccion: "Turquía" },
  { id: "TUR-14", nombre: "Ozcan", posicion: "MED", precio: 15, seleccion: "Turquía" },
  { id: "TUR-15", nombre: "Yuksek", posicion: "MED", precio: 12, seleccion: "Turquía" },
  { id: "TUR-16", nombre: "Ayhan", posicion: "MED", precio: 12, seleccion: "Turquía" },
  { id: "TUR-17", nombre: "Yokuslu", posicion: "MED", precio: 10, seleccion: "Turquía" },
  { id: "TUR-18", nombre: "Yildiz", posicion: "DEL", precio: 30, seleccion: "Turquía" },
  { id: "TUR-19", nombre: "Akturkoglu", posicion: "DEL", precio: 20, seleccion: "Turquía" },
  { id: "TUR-20", nombre: "Yilmaz", posicion: "DEL", precio: 20, seleccion: "Turquía" },
  { id: "TUR-21", nombre: "Kahveci", posicion: "DEL", precio: 15, seleccion: "Turquía" },
  { id: "TUR-22", nombre: "Akgun", posicion: "DEL", precio: 12, seleccion: "Turquía" },
  { id: "TUR-23", nombre: "Yazici", posicion: "DEL", precio: 12, seleccion: "Turquía" },
  { id: "TUR-24", nombre: "Tosun", posicion: "DEL", precio: 10, seleccion: "Turquía" },
  { id: "TUR-25", nombre: "Kilicsoy", posicion: "DEL", precio: 10, seleccion: "Turquía" },
  { id: "TUR-26", nombre: "Yildirim", posicion: "DEL", precio: 8, seleccion: "Turquía" },
  // GEORGIA
  { id: "GEO-01", nombre: "Mamardashvili", posicion: "POR", precio: 40, seleccion: "Georgia" },
  { id: "GEO-02", nombre: "Loria", posicion: "POR", precio: 7, seleccion: "Georgia" },
  { id: "GEO-03", nombre: "Gugeshashvili", posicion: "POR", precio: 7, seleccion: "Georgia" },
  { id: "GEO-04", nombre: "Kashia", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-05", nombre: "Kvirkvelia", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-06", nombre: "Kakabadze", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-07", nombre: "Dvali", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-08", nombre: "Lochoshvili", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-09", nombre: "Gvelesiani", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-10", nombre: "Gocholeishvili", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-11", nombre: "Tabidze", posicion: "DEF", precio: 7, seleccion: "Georgia" },
  { id: "GEO-12", nombre: "Kochorashvili", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-13", nombre: "Kiteishvili", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-14", nombre: "Chakvetadze", posicion: "MED", precio: 8, seleccion: "Georgia" },
  { id: "GEO-15", nombre: "Lobzhanidze", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-16", nombre: "Shengelia", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-17", nombre: "Altunashvili", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-18", nombre: "Kvekveskiri", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-19", nombre: "Sigua", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-20", nombre: "Mekvabishvili", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-21", nombre: "Tsitaishvili", posicion: "MED", precio: 7, seleccion: "Georgia" },
  { id: "GEO-22", nombre: "Kvaratskhelia", posicion: "DEL", precio: 61, seleccion: "Georgia" },
  { id: "GEO-23", nombre: "Mikautadze", posicion: "DEL", precio: 20, seleccion: "Georgia" },
  { id: "GEO-24", nombre: "Zivzivadze", posicion: "DEL", precio: 7, seleccion: "Georgia" },
  { id: "GEO-25", nombre: "Kvilitaia", posicion: "DEL", precio: 7, seleccion: "Georgia" },
  { id: "GEO-26", nombre: "Davitashvili", posicion: "DEL", precio: 7, seleccion: "Georgia" },
  // PORTUGAL
  { id: "POR-01", nombre: "Diogo Costa", posicion: "POR", precio: 38, seleccion: "Portugal" },
  { id: "POR-02", nombre: "Rui Patrício", posicion: "POR", precio: 15, seleccion: "Portugal" },
  { id: "POR-03", nombre: "José Sá", posicion: "POR", precio: 15, seleccion: "Portugal" },
  { id: "POR-04", nombre: "Cancelo", posicion: "DEF", precio: 52, seleccion: "Portugal" },
  { id: "POR-05", nombre: "Dalot", posicion: "DEF", precio: 40, seleccion: "Portugal" },
  { id: "POR-06", nombre: "Ruben Dias", posicion: "DEF", precio: 50, seleccion: "Portugal" },
  { id: "POR-07", nombre: "Pepe", posicion: "DEF", precio: 20, seleccion: "Portugal" },
  { id: "POR-08", nombre: "Inacio", posicion: "DEF", precio: 35, seleccion: "Portugal" },
  { id: "POR-09", nombre: "Nuno Mendes", posicion: "DEF", precio: 45, seleccion: "Portugal" },
  { id: "POR-10", nombre: "Antonio Silva", posicion: "DEF", precio: 30, seleccion: "Portugal" },
  { id: "POR-11", nombre: "Semedo", posicion: "DEF", precio: 25, seleccion: "Portugal" },
  { id: "POR-12", nombre: "Danilo", posicion: "DEF", precio: 25, seleccion: "Portugal" },
  { id: "POR-13", nombre: "Palhinha", posicion: "MED", precio: 40, seleccion: "Portugal" },
  { id: "POR-14", nombre: "Vitinha", posicion: "MED", precio: 38, seleccion: "Portugal" },
  { id: "POR-15", nombre: "Bruno Fernandes", posicion: "MED", precio: 61, seleccion: "Portugal" },
  { id: "POR-16", nombre: "Otavio", posicion: "MED", precio: 30, seleccion: "Portugal" },
  { id: "POR-17", nombre: "Ruben Neves", posicion: "MED", precio: 30, seleccion: "Portugal" },
  { id: "POR-18", nombre: "Joao Neves", posicion: "MED", precio: 30, seleccion: "Portugal" },
  { id: "POR-19", nombre: "Bernardo Silva", posicion: "DEL", precio: 58, seleccion: "Portugal" },
  { id: "POR-20", nombre: "Cristiano Ronaldo", posicion: "DEL", precio: 55, seleccion: "Portugal" },
  { id: "POR-21", nombre: "Leao", posicion: "DEL", precio: 52, seleccion: "Portugal" },
  { id: "POR-22", nombre: "Joao Félix", posicion: "DEL", precio: 45, seleccion: "Portugal" },
  { id: "POR-23", nombre: "Diogo Jota", posicion: "DEL", precio: 42, seleccion: "Portugal" },
  { id: "POR-24", nombre: "Gonçalo Ramos", posicion: "DEL", precio: 35, seleccion: "Portugal" },
  { id: "POR-25", nombre: "Pedro Neto", posicion: "DEL", precio: 30, seleccion: "Portugal" },
  { id: "POR-26", nombre: "Conceição", posicion: "DEL", precio: 25, seleccion: "Portugal" },
  // REPÚBLICA CHECA
  { id: "CZE-01", nombre: "Stanek", posicion: "POR", precio: 10, seleccion: "República Checa" },
  { id: "CZE-02", nombre: "Kovar", posicion: "POR", precio: 10, seleccion: "República Checa" },
  { id: "CZE-03", nombre: "Jaros", posicion: "POR", precio: 7, seleccion: "República Checa" },
  { id: "CZE-04", nombre: "Coufal", posicion: "DEF", precio: 20, seleccion: "República Checa" },
  { id: "CZE-05", nombre: "Holes", posicion: "DEF", precio: 15, seleccion: "República Checa" },
  { id: "CZE-06", nombre: "Hranac", posicion: "DEF", precio: 10, seleccion: "República Checa" },
  { id: "CZE-07", nombre: "Krejci", posicion: "DEF", precio: 15, seleccion: "República Checa" },
  { id: "CZE-08", nombre: "Vitik", posicion: "DEF", precio: 10, seleccion: "República Checa" },
  { id: "CZE-09", nombre: "Zima", posicion: "DEF", precio: 10, seleccion: "República Checa" },
  { id: "CZE-10", nombre: "Jurasek", posicion: "DEF", precio: 12, seleccion: "República Checa" },
  { id: "CZE-11", nombre: "Vlcek", posicion: "DEF", precio: 8, seleccion: "República Checa" },
  { id: "CZE-12", nombre: "Doudera", posicion: "DEF", precio: 10, seleccion: "República Checa" },
  { id: "CZE-13", nombre: "Soucek", posicion: "MED", precio: 35, seleccion: "República Checa" },
  { id: "CZE-14", nombre: "Provod", posicion: "MED", precio: 15, seleccion: "República Checa" },
  { id: "CZE-15", nombre: "Barak", posicion: "MED", precio: 15, seleccion: "República Checa" },
  { id: "CZE-16", nombre: "Sadilek", posicion: "MED", precio: 12, seleccion: "República Checa" },
  { id: "CZE-17", nombre: "Sulc", posicion: "MED", precio: 10, seleccion: "República Checa" },
  { id: "CZE-18", nombre: "Lingr", posicion: "MED", precio: 10, seleccion: "República Checa" },
  { id: "CZE-19", nombre: "Cerv", posicion: "MED", precio: 8, seleccion: "República Checa" },
  { id: "CZE-20", nombre: "Matej Jurasek", posicion: "MED", precio: 8, seleccion: "República Checa" },
  { id: "CZE-21", nombre: "Schick", posicion: "DEL", precio: 34, seleccion: "República Checa" },
  { id: "CZE-22", nombre: "Hlozek", posicion: "DEL", precio: 20, seleccion: "República Checa" },
  { id: "CZE-23", nombre: "Kuchta", posicion: "DEL", precio: 15, seleccion: "República Checa" },
  { id: "CZE-24", nombre: "Chytil", posicion: "DEL", precio: 12, seleccion: "República Checa" },
  { id: "CZE-25", nombre: "Chory", posicion: "DEL", precio: 10, seleccion: "República Checa" },
  { id: "CZE-26", nombre: "Cerny", posicion: "DEL", precio: 15, seleccion: "República Checa" }
];